<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-MEPT26D" failures="2" tests="4" name="Test" time="19.149" errors="0" timestamp="2024-02-08T12:27:06 IST">
  <testcase classname="ListenerMethods.SoftAssertion2" name="assertion" time="17.983">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Automation Testing Practice1] but found [Automation Testing Practice]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Automation Testing Practice1] but found [Automation Testing Practice]
at ListenerMethods.SoftAssertion2.assertion(SoftAssertion2.java:37)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- assertion -->
  <testcase classname="ListenerMethods.HardAssertion" name="assertion" time="18.022">
    <failure type="java.lang.AssertionError" message="expected [Automation Testing Practice1] but found [Automation Testing Practice]">
      <![CDATA[java.lang.AssertionError: expected [Automation Testing Practice1] but found [Automation Testing Practice]
at ListenerMethods.HardAssertion.assertion(HardAssertion.java:24)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- assertion -->
  <testcase classname="ListenerMethods.SoftAssertion1" name="assertion" time="18.903"/>
  <testcase classname="ListenerMethods.HardAssertion1" name="assertion" time="19.092"/>
</testsuite> <!-- Test -->
